In [1]:
print("all ok")

all ok


In [2]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [3]:
documents =[
    "people watch movies",
    "people watch cricket",
    "people like movies",
    "people like cricket"
]

##list comprehension##

In [6]:
tokens = [sentence.lower().split() for sentence in documents]

In [7]:
tokens

[['people', 'watch', 'movies'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movies'],
 ['people', 'like', 'cricket']]

In [8]:
all_words = [[word] for sentence in tokens for word in sentence]

In [9]:
all_words

[['people'],
 ['watch'],
 ['movies'],
 ['people'],
 ['watch'],
 ['cricket'],
 ['people'],
 ['like'],
 ['movies'],
 ['people'],
 ['like'],
 ['cricket']]

In [ ]:
encoder = OneHotEncoder(sparse_output=False)

In [ ]:
encoder.fit (all_words)
encoder.categories_[0]

array(['cricket', 'like', 'movies', 'people', 'watch'], dtype=object)

In [12]:
print("vocabulary: ", encoder.categories_[0])

vocabulary:  ['cricket' 'like' 'movies' 'people' 'watch']


In [13]:
for sentence in tokens:
    print(sentence)

['people', 'watch', 'movies']
['people', 'watch', 'cricket']
['people', 'like', 'movies']
['people', 'like', 'cricket']


In [19]:
for sentence in tokens:
    encoded_sentence = encoder.transform([[word] for word in sentence])
    encoded_sentence = encoded_sentence.astype(int)
    print("\nEncoded sentence:", sentence)
    print("Encoded:", encoded_sentence)


Encoded sentence: ['people', 'watch', 'movies']
Encoded: [[0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 1 0 0]]

Encoded sentence: ['people', 'watch', 'cricket']
Encoded: [[0 0 0 1 0]
 [0 0 0 0 1]
 [1 0 0 0 0]]

Encoded sentence: ['people', 'like', 'movies']
Encoded: [[0 0 0 1 0]
 [0 1 0 0 0]
 [0 0 1 0 0]]

Encoded sentence: ['people', 'like', 'cricket']
Encoded: [[0 0 0 1 0]
 [0 1 0 0 0]
 [1 0 0 0 0]]


BOW

In [22]:
from sklearn.feature_extraction.text import CountVectorizer

In [23]:
documents = ["people watch movie and watch movie again", 
             "people watch cricket and watch cricket",
             "people like movie and like movie a lot",
             "people like cricket"]

In [24]:
bow = CountVectorizer()
bow_matrix = bow.fit_transform(documents)

In [25]:
bow_matrix

<4x8 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [26]:
bow_matrix.toarray()

array([[1, 1, 0, 0, 0, 2, 1, 2],
       [0, 1, 2, 0, 0, 0, 1, 2],
       [0, 1, 0, 2, 1, 2, 1, 0],
       [0, 0, 1, 1, 0, 0, 1, 0]], dtype=int64)

In [27]:
bow.get_feature_names_out()

array(['again', 'and', 'cricket', 'like', 'lot', 'movie', 'people',
       'watch'], dtype=object)

In [28]:
print("vocabulary:\n", bow.get_feature_names_out())

vocabulary:
 ['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']
